In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv("data/Purbaya Sadewa: Pendirian dalam Berkebijakan Itu Penting.csv")
df

,Date,Username,Comment,Like
0,2026-03-30T22:23:07Z,@bengkelkayumakassar3534,Wajar lah pak Prabowo mengedepankan kepentinga...,0
1,2026-03-28T21:55:14Z,@CarpenterToys,Subsidi BBM mau dialihkan Full MBG Bungg 😂,2
2,2026-03-28T04:37:15Z,@AghataSahat,Diskusi yang membuka mata tentang indonesia 🤝,0
3,2026-03-28T03:53:52Z,@Wiranto-y1f5l,Sy senang lihat podcast,0
4,2026-03-27T16:00:24Z,@AdrianusBambangAdiWibowo,Cl simed it ready to receive this blessing fro...,0
...,...,...,...,...
3789,2025-12-03T09:45:21Z,@PasukanRevolusi-x1w,🔥,0
3790,2025-12-03T09:46:57Z,@norichnostory,🔥,0
3791,2025-12-03T09:47:55Z,@RevolusiReal,🔥,0
3792,2025-12-03T09:33:18Z,@amaliarifatulatifah6834,❤,1
3793,2025-12-03T09:30:58Z,@patrickk9169,Here we go!,1

In [3]:
df = df[['Date', 'Comment']]
df

                      Date                                            Comment
0     2026-03-30T22:23:07Z  Wajar lah pak Prabowo mengedepankan kepentinga...
1     2026-03-28T21:55:14Z         Subsidi BBM mau dialihkan Full MBG Bungg 😂
2     2026-03-28T04:37:15Z      Diskusi yang membuka mata tentang indonesia 🤝
3     2026-03-28T03:53:52Z                            Sy senang lihat podcast
4     2026-03-27T16:00:24Z  Cl simed it ready to receive this blessing fro...
...                    ...                                                ...
3789  2025-12-03T09:45:21Z                                                  🔥
3790  2025-12-03T09:46:57Z                                                  🔥
3791  2025-12-03T09:47:55Z                                                  🔥
3792  2025-12-03T09:33:18Z                                                  ❤
3793  2025-12-03T09:30:58Z                                        Here we go!

[3794 rows x 2 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3794 entries, 0 to 3793
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     3794 non-null   object
 1   Comment  3794 non-null   object
dtypes: object(2)
memory usage: 59.4+ KB

# Membersihkan data

In [5]:
df = df.copy()

df['Comment'] = (
    df['Comment']
    .astype(str)
    .str.lower()
    .replace('false', pd.NA)
)

# hapus nAn
df = df.dropna(subset=['Comment'])
# Hapus string kosong
df = df[df['Comment'].str.strip() != '']

In [6]:
df.shape

(3794, 2)

In [7]:
#hapus data duplicates
df = df.drop_duplicates(subset=['Comment'])

In [8]:
df.shape

(3656, 2)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df.dropna()

In [11]:
df.shape

(3656, 2)

In [12]:
df.isnull().sum()

Date       0
Comment    0
dtype: int64

In [13]:
df.shape

(3656, 2)

In [14]:
def clean_yt_text(text):
  text = re.sub(r'<.*?>', '', text)  # hapus HTML tag (penting!)
  text = re.sub(r'@[A-Za-z0-9_]+', '', text)  # hapus mention seperti @username
  text = re.sub(r'#\w+', '', text) # hapus hashtag seperti #viral
  text = re.sub(r'https?://\S+', '', text) # hapus URL/link (http/https)

  text = re.sub(r'(.)\1{2,}', r'\1', text)  # ubah huruf berulang (contoh: baguuuus → bagus)
  text = re.sub(r'[^a-zA-Z ]', ' ', text) # hapus karakter selain huruf dan spasi
  text = re.sub(r'\s+', ' ', text).strip() # hapus spasi berlebih & rapikan

  return text

df['Comment'] = df['Comment'].apply(clean_yt_text)

In [15]:
#hapus NaN, string kosong dan spasi 
df = df[df['Comment'].astype(str).str.strip().ne('')]

In [16]:
df.shape

(3543, 2)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3543 entries, 0 to 3793
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     3543 non-null   object
 1   Comment  3543 non-null   object
dtypes: object(2)
memory usage: 83.0+ KB

In [18]:
df.head(10)

                    Date                                            Comment
0   2026-03-30T22:23:07Z  wajar lah pak prabowo mengedepankan kepentinga...
1   2026-03-28T21:55:14Z           subsidi bbm mau dialihkan full mbg bungg
2   2026-03-28T04:37:15Z        diskusi yang membuka mata tentang indonesia
3   2026-03-28T03:53:52Z                            sy senang lihat podcast
4   2026-03-27T16:00:24Z  cl simed it ready to receive this blessing fro...
6   2026-03-25T23:31:37Z                                           flamingo
7   2026-03-25T23:31:22Z                       ie don t come back who cares
8   2026-03-25T23:31:01Z  notice zamani came back for raya i can do the ...
9   2026-03-25T23:29:03Z      laffer curve incomplete laffer pareto optimum
10  2026-03-25T14:18:03Z  pemerintah bisa buat perusahaan perusahaan mob...

## simpan data cleaning

In [19]:
df.to_csv("data/hasilCleaning.csv", index=False)