In [14]:
import pandas as pd
import re
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm

In [15]:
df = pd.read_csv("hasilCleaning.csv")
df

                      Date                                            Comment
0     2026-03-21T18:53:55Z                                          a jawab b
1     2026-03-21T18:52:35Z  dari pertanyaan retno aja jawabannya udah gak ...
2     2026-03-21T18:52:20Z  jawabannya panjang lebar tp kurang nyambung ng...
3     2026-03-21T18:48:57Z                                 buktinya mana wowo
4     2026-03-21T18:45:05Z  apakah anda tahu pnm membantu masyarakat atau ...
...                    ...                                                ...
7919  2026-03-19T14:06:52Z               sorry bang di sekolah gua bermanfaat
7920  2026-03-19T14:12:27Z           manfaatnya pendidikan gratis lebih ngena
7921  2026-03-19T14:12:45Z  mbg dari kami yang bayar pajak klw gak dari ma...
7922  2026-03-19T14:21:11Z                  mbg itu apa hanya dari pajak anda
7923  2026-03-19T14:22:08Z  apalagi ganjar pranowo presiden pasti jadi beb...

[7924 rows x 2 columns]

# Normalisasi

In [16]:
normal = {
    'yg': 'yang',
    'thn': 'tahun',
    'bpk': 'bapak',
    'lg': 'lagi',
    'kyk': 'kayak',
    'mkan': 'makan',
    'bljr': 'belajar',
    'tak': 'tidak',
    'dpt': 'dapat',
    'gt': 'gitu',
    'skrg': 'sekarang',
    'trs': 'terus',
    'lu': 'kamu',
    'sj': 'saja',
    'jg': 'juga',
    'ga': 'tidak',
    'gak': 'tidak',
    'kaga': 'tidak',
    'tsb': 'tersebut',
    'udh': 'sudah',
    'sm': 'sama',
    'dy': 'dia',
    'ddpn': 'didepan',
    'makasi': 'makasih',
    'banyakk': 'banyak',
    'mantaap': 'mantap',
    'donk': 'dong',
    'krn': 'karena',
    'jgn': 'jangan',
    'ntar': 'nanti',
    'gg': 'keren',
    'bisaa': 'bisa',
    'klo': 'kalo',
    'amp': 'sampai',
    'kek': 'seperti',
    'utk': 'untuk',
    'pd': 'pada',
    'dgn': 'dengan',
    'bgt': 'banget',
    'km': 'kamu',
    'byk': 'banyak',
    'mrk': 'mereka',
    'blm': 'belum',
    'org': 'orang',
    'dg': 'dengan',
    'lali': 'lupa',
    'gaskeun': 'ayo',
    'idk': 'tidak tahu',
    'karna': 'karena',
    'brita': 'berita',
    'nyerang': 'menyerang',
    'udah': 'sudah',
    'ngerti': 'mengerti',
    'hnya': 'hanya',
    'rkyt': 'rakyat',
    'klas': 'kelas',
    'bnyk': 'banyak',
    'pny': 'punya',
    'tdk': 'tidak',
    'dlm': 'dalam',
    'problem': 'masalah',
    'sdh': 'sudah',
    'pov': 'sudut pandang',
    'tpi': 'tapi',
    'tni': 'tentara'
    
    
}
def normalisasi(teks):
    tokens = str(teks).split()
    hasil = []

    for kata in tokens:
        if kata in normal:
            hasil.append(normal[kata])
        else:
            hasil.append(kata)

    return " ".join(hasil)

# Terapkan ke kolom
df['Comment'] = df['Comment'].apply(normalisasi)
df

                      Date                                            Comment
0     2026-03-21T18:53:55Z                                          a jawab b
1     2026-03-21T18:52:35Z  dari pertanyaan retno aja jawabannya sudah tid...
2     2026-03-21T18:52:20Z  jawabannya panjang lebar tp kurang nyambung ng...
3     2026-03-21T18:48:57Z                                 buktinya mana wowo
4     2026-03-21T18:45:05Z  apakah anda tahu pnm membantu masyarakat atau ...
...                    ...                                                ...
7919  2026-03-19T14:06:52Z               sorry bang di sekolah gua bermanfaat
7920  2026-03-19T14:12:27Z           manfaatnya pendidikan gratis lebih ngena
7921  2026-03-19T14:12:45Z  mbg dari kami yang bayar pajak klw tidak dari ...
7922  2026-03-19T14:21:11Z                  mbg itu apa hanya dari pajak anda
7923  2026-03-19T14:22:08Z  apalagi ganjar pranowo presiden pasti jadi beb...

[7924 rows x 2 columns]

# Tokenize

In [17]:
tokenized = df['Comment'].apply(lambda x:x.split())
tokenized

0                                           [a, jawab, b]
1       [dari, pertanyaan, retno, aja, jawabannya, sud...
2       [jawabannya, panjang, lebar, tp, kurang, nyamb...
3                                  [buktinya, mana, wowo]
4       [apakah, anda, tahu, pnm, membantu, masyarakat...
                              ...
7919          [sorry, bang, di, sekolah, gua, bermanfaat]
7920       [manfaatnya, pendidikan, gratis, lebih, ngena]
7921    [mbg, dari, kami, yang, bayar, pajak, klw, tid...
7922            [mbg, itu, apa, hanya, dari, pajak, anda]
7923    [apalagi, ganjar, pranowo, presiden, pasti, ja...
Name: Comment, Length: 7924, dtype: object

In [18]:
print(type(tokenized[0]))
print(type(tokenized[0][0]))

<class 'list'>
<class 'str'>

In [19]:
df.to_csv("hasilTokenize.csv", index=False)
df

                      Date                                            Comment
0     2026-03-21T18:53:55Z                                          a jawab b
1     2026-03-21T18:52:35Z  dari pertanyaan retno aja jawabannya sudah tid...
2     2026-03-21T18:52:20Z  jawabannya panjang lebar tp kurang nyambung ng...
3     2026-03-21T18:48:57Z                                 buktinya mana wowo
4     2026-03-21T18:45:05Z  apakah anda tahu pnm membantu masyarakat atau ...
...                    ...                                                ...
7919  2026-03-19T14:06:52Z               sorry bang di sekolah gua bermanfaat
7920  2026-03-19T14:12:27Z           manfaatnya pendidikan gratis lebih ngena
7921  2026-03-19T14:12:45Z  mbg dari kami yang bayar pajak klw tidak dari ...
7922  2026-03-19T14:21:11Z                  mbg itu apa hanya dari pajak anda
7923  2026-03-19T14:22:08Z  apalagi ganjar pranowo presiden pasti jadi beb...

[7924 rows x 2 columns]

# Filter token

In [20]:
# Tokenizing
df['tokens'] = df['Comment'].apply(lambda x: x.split())

# Filter tokens (hapus kata dengan panjang <= 2)
df['filtered_tokens'] = df['tokens'].apply(
    lambda tokens: [w for w in tokens if len(w) > 2]
)
df['filtered_tokens']

0                                                 [jawab]
1       [dari, pertanyaan, retno, aja, jawabannya, sud...
2       [jawabannya, panjang, lebar, kurang, nyambung,...
3                                  [buktinya, mana, wowo]
4       [apakah, anda, tahu, pnm, membantu, masyarakat...
                              ...
7919              [sorry, bang, sekolah, gua, bermanfaat]
7920       [manfaatnya, pendidikan, gratis, lebih, ngena]
7921    [mbg, dari, kami, yang, bayar, pajak, klw, tid...
7922            [mbg, itu, apa, hanya, dari, pajak, anda]
7923    [apalagi, ganjar, pranowo, presiden, pasti, ja...
Name: filtered_tokens, Length: 7924, dtype: object

In [21]:
# Drop kolom
df = df.drop(columns=['Comment', 'tokens'], errors='ignore')

# Rename kolom
df = df.rename(columns={'filtered_tokens': 'Comment'})

df.to_csv("hasilFilterToken.csv", index=False)
df

                      Date                                            Comment
0     2026-03-21T18:53:55Z                                            [jawab]
1     2026-03-21T18:52:35Z  [dari, pertanyaan, retno, aja, jawabannya, sud...
2     2026-03-21T18:52:20Z  [jawabannya, panjang, lebar, kurang, nyambung,...
3     2026-03-21T18:48:57Z                             [buktinya, mana, wowo]
4     2026-03-21T18:45:05Z  [apakah, anda, tahu, pnm, membantu, masyarakat...
...                    ...                                                ...
7919  2026-03-19T14:06:52Z            [sorry, bang, sekolah, gua, bermanfaat]
7920  2026-03-19T14:12:27Z     [manfaatnya, pendidikan, gratis, lebih, ngena]
7921  2026-03-19T14:12:45Z  [mbg, dari, kami, yang, bayar, pajak, klw, tid...
7922  2026-03-19T14:21:11Z          [mbg, itu, apa, hanya, dari, pajak, anda]
7923  2026-03-19T14:22:08Z  [apalagi, ganjar, pranowo, presiden, pasti, ja...

[7924 rows x 2 columns]

# Stopwords

In [22]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

# 1. STOPWORDS DASAR
factory = StopWordRemoverFactory()
stopwords = set(factory.get_stop_words())

# 2. TAMBAHAN STOPWORDS
custom_stopwords = {
    'yang','dan','di','ke','dari','ini','itu','jadi','nya',
    'pak','bapak','mbak','lah','sih'
}

stopwords = stopwords.union(custom_stopwords)

# 3. PERTAHANKAN NEGASI
negation_words = {"tidak", "bukan", "jangan"}
stopwords = stopwords - negation_words

# 4. NORMALISASI KATA
replace_dict = {
    'pak': 'prabowo',
    'bapak': 'prabowo'
}

def normalize_tokens(tokens):
    return [replace_dict.get(w, w) for w in tokens]

# 5. STOPWORD REMOVAL
df['tokens_stopword'] = df['Comment'].apply(
    lambda tokens: [
        w.strip().lower() for w in tokens
        if w.strip().lower() not in stopwords
    ]
)

# 6. NORMALISASI SETELAH STOPWORD
df['tokens_stopword'] = df['tokens_stopword'].apply(normalize_tokens)

# 7. GABUNG KEMBALI KE TEKS
df['clean_text'] = df['tokens_stopword'].apply(lambda x: " ".join(x))

In [23]:
df.to_csv("hasilStopword.csv", index=False)
df

,Date,Comment,tokens_stopword,clean_text
0,2026-03-21T18:53:55Z,[jawab],[jawab],jawab
1,2026-03-21T18:52:35Z,"[dari, pertanyaan, retno, aja, jawabannya, sud...","[pertanyaan, retno, aja, jawabannya, tidak, ny...",pertanyaan retno aja jawabannya tidak nyambung...
2,2026-03-21T18:52:20Z,"[jawabannya, panjang, lebar, kurang, nyambung,...","[jawabannya, panjang, lebar, kurang, nyambung,...",jawabannya panjang lebar kurang nyambung ngdab...
3,2026-03-21T18:48:57Z,"[buktinya, mana, wowo]","[buktinya, mana, wowo]",buktinya mana wowo
4,2026-03-21T18:45:05Z,"[apakah, anda, tahu, pnm, membantu, masyarakat...","[tahu, pnm, membantu, masyarakat, membudidayak...",tahu pnm membantu masyarakat membudidayakan pi...
...,...,...,...,...
7919,2026-03-19T14:06:52Z,"[sorry, bang, sekolah, gua, bermanfaat]","[sorry, bang, sekolah, gua, bermanfaat]",sorry bang sekolah gua bermanfaat
7920,2026-03-19T14:12:27Z,"[manfaatnya, pendidikan, gratis, lebih, ngena]","[manfaatnya, pendidikan, gratis, lebih, ngena]",manfaatnya pendidikan gratis lebih ngena
7921,2026-03-19T14:12:45Z,"[mbg, dari, kami, yang, bayar, pajak, klw, tid...","[mbg, bayar, pajak, klw, tidak, mana, dana, mb...",mbg bayar pajak klw tidak mana dana mbg pikir ...
7922,2026-03-19T14:21:11Z,"[mbg, itu, apa, hanya, dari, pajak, anda]","[mbg, apa, pajak]",mbg apa pajak
7923,2026-03-19T14:22:08Z,"[apalagi, ganjar, pranowo, presiden, pasti, ja...","[ganjar, pranowo, presiden, beban, jawa, tenga...",ganjar pranowo presiden beban jawa tengah aja ...

# Stemming

In [24]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from tqdm import tqdm
import pandas as pd
import joblib
import os
import re

# 1. CONFIG cache simpan database stemming
CACHE_FILE = "db_stemming.pkl"

# 2. LOAD CACHE
if os.path.exists(CACHE_FILE):
    word_map = joblib.load(CACHE_FILE)
    print(f"✅ Cache loaded ({len(word_map)} kata)")
else:
    word_map = {}
    print("⚠️ Cache baru dibuat")

# 3. INIT STEMMER (sekali)
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# 4. CLEANING TEXT
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z0-9 ]', ' ', text)  # hapus simbol
    text = re.sub(r'\s+', ' ', text).strip()    # hapus spasi ganda
    return text

# 5. STEMMING FUNCTION
def stemming_fast(text):
    text = clean_text(text)
    words = text.split()

    result = []
    for w in words:
        if w in word_map:
            result.append(word_map[w])
        else:
            stem = stemmer.stem(w)
            word_map[w] = stem
            result.append(stem)

    return " ".join(result)


# 6. PROSES DATA
texts = df['tokens_stopword']

hasil = []
for i, text in enumerate(tqdm(texts, desc="Stemming")):
    hasil.append(stemming_fast(text))

    # autosave tiap 500 data
    if i % 500 == 0:
        joblib.dump(word_map, CACHE_FILE)

df['stemmed'] = hasil

# 7. SAVE HASIL
df.to_csv("hasilStemming.csv", index=False)
joblib.dump(word_map, CACHE_FILE)

print("✅ Selesai! Data & cache tersimpan 🚀")

✅ Cache loaded (18822 kata)

Stemming: 100%|███████████████████████████| 7924/7924 [00:02<00:00, 3180.43it/s]

✅ Selesai! Data & cache tersimpan 🚀

In [25]:
df = pd.read_csv('hasilStemming.csv')
df

,Date,Comment,tokens_stopword,clean_text,stemmed
0,2026-03-21T18:53:55Z,['jawab'],['jawab'],jawab,jawab
1,2026-03-21T18:52:35Z,"['dari', 'pertanyaan', 'retno', 'aja', 'jawaba...","['pertanyaan', 'retno', 'aja', 'jawabannya', '...",pertanyaan retno aja jawabannya tidak nyambung...,tanya retno aja jawab tidak nyambung wkwkwkwkwk
2,2026-03-21T18:52:20Z,"['jawabannya', 'panjang', 'lebar', 'kurang', '...","['jawabannya', 'panjang', 'lebar', 'kurang', '...",jawabannya panjang lebar kurang nyambung ngdab...,jawab panjang lebar kurang nyambung ngdabrus d...
3,2026-03-21T18:48:57Z,"['buktinya', 'mana', 'wowo']","['buktinya', 'mana', 'wowo']",buktinya mana wowo,bukti mana wowo
4,2026-03-21T18:45:05Z,"['apakah', 'anda', 'tahu', 'pnm', 'membantu', ...","['tahu', 'pnm', 'membantu', 'masyarakat', 'mem...",tahu pnm membantu masyarakat membudidayakan pi...,tahu pnm bantu masyarakat membudidayakan piuta...
...,...,...,...,...,...
7919,2026-03-19T14:06:52Z,"['sorry', 'bang', 'sekolah', 'gua', 'bermanfaat']","['sorry', 'bang', 'sekolah', 'gua', 'bermanfaat']",sorry bang sekolah gua bermanfaat,sorry bang sekolah gua manfaat
7920,2026-03-19T14:12:27Z,"['manfaatnya', 'pendidikan', 'gratis', 'lebih'...","['manfaatnya', 'pendidikan', 'gratis', 'lebih'...",manfaatnya pendidikan gratis lebih ngena,manfaat didik gratis lebih ngena
7921,2026-03-19T14:12:45Z,"['mbg', 'dari', 'kami', 'yang', 'bayar', 'paja...","['mbg', 'bayar', 'pajak', 'klw', 'tidak', 'man...",mbg bayar pajak klw tidak mana dana mbg pikir ...,mbg bayar pajak klw tidak mana dana mbg pikir ...
7922,2026-03-19T14:21:11Z,"['mbg', 'itu', 'apa', 'hanya', 'dari', 'pajak'...","['mbg', 'apa', 'pajak']",mbg apa pajak,mbg apa pajak
7923,2026-03-19T14:22:08Z,"['apalagi', 'ganjar', 'pranowo', 'presiden', '...","['ganjar', 'pranowo', 'presiden', 'beban', 'ja...",ganjar pranowo presiden beban jawa tengah aja ...,ganjar pranowo presiden beban jawa tengah aja ...

Ubah kolom stemmed ke Comment dan simpan ke file hasilPreprocessing .csv

In [26]:
hasil = df[['stemmed']].rename(columns={'stemmed': 'Comment'}).to_csv("hasilPreprocessing.csv", index=False)
#hasil.to_csv("hasilPreprocessing.csv", index=False)
hasil = pd.read_csv("hasilPreprocessing.csv")
hasil

                                                Comment
0                                                 jawab
1       tanya retno aja jawab tidak nyambung wkwkwkwkwk
2     jawab panjang lebar kurang nyambung ngdabrus d...
3                                       bukti mana wowo
4     tahu pnm bantu masyarakat membudidayakan piuta...
...                                                 ...
7919                     sorry bang sekolah gua manfaat
7920                   manfaat didik gratis lebih ngena
7921  mbg bayar pajak klw tidak mana dana mbg pikir ...
7922                                      mbg apa pajak
7923  ganjar pranowo presiden beban jawa tengah aja ...

[7924 rows x 1 columns]