In [14]:
import pandas as pd
import re
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm

In [15]:
df = pd.read_csv("data/hasilCleaning.csv")
df

                      Date                                            Comment
0     2026-03-30T22:23:07Z  wajar lah pak prabowo mengedepankan kepentinga...
1     2026-03-28T21:55:14Z           subsidi bbm mau dialihkan full mbg bungg
2     2026-03-28T04:37:15Z        diskusi yang membuka mata tentang indonesia
3     2026-03-28T03:53:52Z                            sy senang lihat podcast
4     2026-03-27T16:00:24Z  cl simed it ready to receive this blessing fro...
...                    ...                                                ...
3538  2025-12-03T09:52:59Z                                           herewego
3539  2025-12-03T09:51:24Z  baru kali ini nonton youtube konten nya belum ...
3540  2025-12-03T09:43:38Z  gass pak purbaya kami masyarakat selalu menduk...
3541  2025-12-03T09:39:18Z                               yang ditunggu tunggu
3542  2025-12-03T09:30:58Z                                         here we go

[3543 rows x 2 columns]

# Normalisasi

In [16]:
normal = {
    'yg': 'yang',
    'thn': 'tahun',
    'bpk': 'bapak',
    'lg': 'lagi',
    'kyk': 'kayak',
    'mkan': 'makan',
    'bljr': 'belajar',
    'tak': 'tidak',
    'dpt': 'dapat',
    'gt': 'gitu',
    'skrg': 'sekarang',
    'trs': 'terus',
    'lu': 'kamu',
    'sj': 'saja',
    'jg': 'juga',
    'ga': 'tidak',
    'gak': 'tidak',
    'kaga': 'tidak',
    'tsb': 'tersebut',
    'udh': 'sudah',
    'sm': 'sama',
    'dy': 'dia',
    'ddpn': 'didepan',
    'makasi': 'makasih',
    'banyakk': 'banyak',
    'mantaap': 'mantap',
    'donk': 'dong',
    'krn': 'karena',
    'jgn': 'jangan',
    'ntar': 'nanti',
    'gg': 'keren',
    'bisaa': 'bisa',
    'klo': 'kalo',
    'amp': 'sampai',
    'kek': 'seperti',
    'utk': 'untuk',
    'pd': 'pada',
    'dgn': 'dengan',
    'bgt': 'banget',
    'km': 'kamu',
    'byk': 'banyak',
    'mrk': 'mereka',
    'blm': 'belum',
    'org': 'orang',
    'dg': 'dengan',
    'lali': 'lupa',
    'gaskeun': 'ayo',
    'idk': 'tidak tahu',
    'karna': 'karena',
    'brita': 'berita',
    'nyerang': 'menyerang',
    'udah': 'sudah',
    'ngerti': 'mengerti',
    'hnya': 'hanya',
    'rkyt': 'rakyat',
    'klas': 'kelas',
    'bnyk': 'banyak',
    'pny': 'punya',
    'tdk': 'tidak',
    'dlm': 'dalam',
    'problem': 'masalah',
    'sdh': 'sudah',
    'pov': 'sudut pandang',
    'tpi': 'tapi',
    'tni': 'tentara'
    
    
}
def normalisasi(teks):
    tokens = str(teks).split()
    hasil = []

    for kata in tokens:
        if kata in normal:
            hasil.append(normal[kata])
        else:
            hasil.append(kata)

    return " ".join(hasil)

# Terapkan ke kolom
df['Comment'] = df['Comment'].apply(normalisasi)
df

                      Date                                            Comment
0     2026-03-30T22:23:07Z  wajar lah pak prabowo mengedepankan kepentinga...
1     2026-03-28T21:55:14Z           subsidi bbm mau dialihkan full mbg bungg
2     2026-03-28T04:37:15Z        diskusi yang membuka mata tentang indonesia
3     2026-03-28T03:53:52Z                            sy senang lihat podcast
4     2026-03-27T16:00:24Z  cl simed it ready to receive this blessing fro...
...                    ...                                                ...
3538  2025-12-03T09:52:59Z                                           herewego
3539  2025-12-03T09:51:24Z  baru kali ini nonton youtube konten nya belum ...
3540  2025-12-03T09:43:38Z  gass pak purbaya kami masyarakat selalu menduk...
3541  2025-12-03T09:39:18Z                               yang ditunggu tunggu
3542  2025-12-03T09:30:58Z                                         here we go

[3543 rows x 2 columns]

# Tokenize

In [17]:
tokenized = df['Comment'].apply(lambda x:x.split())
tokenized

0       [wajar, lah, pak, prabowo, mengedepankan, kepe...
1        [subsidi, bbm, mau, dialihkan, full, mbg, bungg]
2       [diskusi, yang, membuka, mata, tentang, indone...
3                            [sy, senang, lihat, podcast]
4       [cl, simed, it, ready, to, receive, this, bles...
                              ...
3538                                           [herewego]
3539    [baru, kali, ini, nonton, youtube, konten, nya...
3540    [gass, pak, purbaya, kami, masyarakat, selalu,...
3541                             [yang, ditunggu, tunggu]
3542                                       [here, we, go]
Name: Comment, Length: 3543, dtype: object

In [18]:
print(type(tokenized[0]))
print(type(tokenized[0][0]))

<class 'list'>
<class 'str'>

In [19]:
df.to_csv("data/hasilTokenize.csv", index=False)
df

                      Date                                            Comment
0     2026-03-30T22:23:07Z  wajar lah pak prabowo mengedepankan kepentinga...
1     2026-03-28T21:55:14Z           subsidi bbm mau dialihkan full mbg bungg
2     2026-03-28T04:37:15Z        diskusi yang membuka mata tentang indonesia
3     2026-03-28T03:53:52Z                            sy senang lihat podcast
4     2026-03-27T16:00:24Z  cl simed it ready to receive this blessing fro...
...                    ...                                                ...
3538  2025-12-03T09:52:59Z                                           herewego
3539  2025-12-03T09:51:24Z  baru kali ini nonton youtube konten nya belum ...
3540  2025-12-03T09:43:38Z  gass pak purbaya kami masyarakat selalu menduk...
3541  2025-12-03T09:39:18Z                               yang ditunggu tunggu
3542  2025-12-03T09:30:58Z                                         here we go

[3543 rows x 2 columns]

# Filter token

In [20]:
# Tokenizing
df['tokens'] = df['Comment'].apply(lambda x: x.split())

# Filter tokens (hapus kata dengan panjang <= 2)
df['filtered_tokens'] = df['tokens'].apply(
    lambda tokens: [w for w in tokens if len(w) > 2]
)
df['filtered_tokens']

0       [wajar, lah, pak, prabowo, mengedepankan, kepe...
1        [subsidi, bbm, mau, dialihkan, full, mbg, bungg]
2       [diskusi, yang, membuka, mata, tentang, indone...
3                                [senang, lihat, podcast]
4       [simed, ready, receive, this, blessing, from, ...
                              ...
3538                                           [herewego]
3539    [baru, kali, ini, nonton, youtube, konten, nya...
3540    [gass, pak, purbaya, kami, masyarakat, selalu,...
3541                             [yang, ditunggu, tunggu]
3542                                               [here]
Name: filtered_tokens, Length: 3543, dtype: object

In [21]:
# Drop kolom
df = df.drop(columns=['Comment', 'tokens'], errors='ignore')

# Rename kolom
df = df.rename(columns={'filtered_tokens': 'Comment'})

df.to_csv("data/hasilFilterToken.csv", index=False)
df

                      Date                                            Comment
0     2026-03-30T22:23:07Z  [wajar, lah, pak, prabowo, mengedepankan, kepe...
1     2026-03-28T21:55:14Z   [subsidi, bbm, mau, dialihkan, full, mbg, bungg]
2     2026-03-28T04:37:15Z  [diskusi, yang, membuka, mata, tentang, indone...
3     2026-03-28T03:53:52Z                           [senang, lihat, podcast]
4     2026-03-27T16:00:24Z  [simed, ready, receive, this, blessing, from, ...
...                    ...                                                ...
3538  2025-12-03T09:52:59Z                                         [herewego]
3539  2025-12-03T09:51:24Z  [baru, kali, ini, nonton, youtube, konten, nya...
3540  2025-12-03T09:43:38Z  [gass, pak, purbaya, kami, masyarakat, selalu,...
3541  2025-12-03T09:39:18Z                           [yang, ditunggu, tunggu]
3542  2025-12-03T09:30:58Z                                             [here]

[3543 rows x 2 columns]

# Stopwords

In [22]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

# 1. STOPWORDS DASAR
factory = StopWordRemoverFactory()
stopwords = set(factory.get_stop_words())

# 2. TAMBAHAN STOPWORDS
custom_stopwords = {
    'yang','dan','di','ke','dari','ini','itu','jadi','nya',
    'pak','bapak','mbak','lah','sih', 'quot'
}

stopwords = stopwords.union(custom_stopwords)

# 3. PERTAHANKAN NEGASI
negation_words = {"tidak", "bukan", "jangan"}
stopwords = stopwords - negation_words

# 4. NORMALISASI KATA
replace_dict = {
    'pur': 'purbaya',
}

def normalize_tokens(tokens):
    return [replace_dict.get(w, w) for w in tokens]

# 5. STOPWORD REMOVAL
df['tokens_stopword'] = df['Comment'].apply(
    lambda tokens: [
        w.strip().lower() for w in tokens
        if w.strip().lower() not in stopwords
    ]
)

# 6. NORMALISASI SETELAH STOPWORD
df['tokens_stopword'] = df['tokens_stopword'].apply(normalize_tokens)

# 7. GABUNG KEMBALI KE TEKS
df['clean_text'] = df['tokens_stopword'].apply(lambda x: " ".join(x))

In [23]:
df.to_csv("data/hasilStopword.csv", index=False)
df

,Date,Comment,tokens_stopword,clean_text
0,2026-03-30T22:23:07Z,"[wajar, lah, pak, prabowo, mengedepankan, kepe...","[wajar, prabowo, mengedepankan, kepentingan, m...",wajar prabowo mengedepankan kepentingan mencet...
1,2026-03-28T21:55:14Z,"[subsidi, bbm, mau, dialihkan, full, mbg, bungg]","[subsidi, bbm, mau, dialihkan, full, mbg, bungg]",subsidi bbm mau dialihkan full mbg bungg
2,2026-03-28T04:37:15Z,"[diskusi, yang, membuka, mata, tentang, indone...","[diskusi, membuka, mata, indonesia]",diskusi membuka mata indonesia
3,2026-03-28T03:53:52Z,"[senang, lihat, podcast]","[senang, lihat, podcast]",senang lihat podcast
4,2026-03-27T16:00:24Z,"[simed, ready, receive, this, blessing, from, ...","[simed, ready, receive, this, blessing, from, ...",simed ready receive this blessing from univers...
...,...,...,...,...
3538,2025-12-03T09:52:59Z,[herewego],[herewego],herewego
3539,2025-12-03T09:51:24Z,"[baru, kali, ini, nonton, youtube, konten, nya...","[baru, kali, nonton, youtube, konten, keluar, ...",baru kali nonton youtube konten keluar ditungguin
3540,2025-12-03T09:43:38Z,"[gass, pak, purbaya, kami, masyarakat, selalu,...","[gass, purbaya, masyarakat, selalu, mendukung,...",gass purbaya masyarakat selalu mendukung pejab...
3541,2025-12-03T09:39:18Z,"[yang, ditunggu, tunggu]","[ditunggu, tunggu]",ditunggu tunggu
3542,2025-12-03T09:30:58Z,[here],[here],here

# Stemming

In [24]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from tqdm import tqdm
import pandas as pd
import joblib
import os
import re

# 1. CONFIG cache simpan database stemming
CACHE_FILE = "db_stemming.pkl"

# 2. LOAD CACHE
if os.path.exists(CACHE_FILE):
    word_map = joblib.load(CACHE_FILE)
    print(f"✅ Cache loaded ({len(word_map)} kata)")
else:
    word_map = {}
    print("⚠️ Cache baru dibuat")

# 3. INIT STEMMER (sekali)
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# 4. CLEANING TEXT
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z0-9 ]', ' ', text)  # hapus simbol
    text = re.sub(r'\s+', ' ', text).strip()    # hapus spasi ganda
    return text

# 5. STEMMING FUNCTION
def stemming_fast(text):
    text = clean_text(text)
    words = text.split()

    result = []
    for w in words:
        if w in word_map:
            result.append(word_map[w])
        else:
            stem = stemmer.stem(w)
            word_map[w] = stem
            result.append(stem)

    return " ".join(result)


# 6. PROSES DATA
texts = df['tokens_stopword']

hasil = []
for i, text in enumerate(tqdm(texts, desc="Stemming")):
    hasil.append(stemming_fast(text))

    # autosave tiap 500 data
    if i % 500 == 0:
        joblib.dump(word_map, CACHE_FILE)

df['stemmed'] = hasil

# 7. SAVE HASIL
df.to_csv("data/hasilStemming.csv", index=False)
joblib.dump(word_map, CACHE_FILE)

print("✅ Selesai! Data & cache tersimpan 🚀")

✅ Cache loaded (6411 kata)

Stemming: 100%|███████████████████████████| 3543/3543 [00:00<00:00, 4729.88it/s]

✅ Selesai! Data & cache tersimpan 🚀

In [25]:
df

,Date,Comment,tokens_stopword,clean_text,stemmed
0,2026-03-30T22:23:07Z,"[wajar, lah, pak, prabowo, mengedepankan, kepe...","[wajar, prabowo, mengedepankan, kepentingan, m...",wajar prabowo mengedepankan kepentingan mencet...,wajar prabowo depan penting cetak man power ti...
1,2026-03-28T21:55:14Z,"[subsidi, bbm, mau, dialihkan, full, mbg, bungg]","[subsidi, bbm, mau, dialihkan, full, mbg, bungg]",subsidi bbm mau dialihkan full mbg bungg,subsidi bbm mau alih full mbg bungg
2,2026-03-28T04:37:15Z,"[diskusi, yang, membuka, mata, tentang, indone...","[diskusi, membuka, mata, indonesia]",diskusi membuka mata indonesia,diskusi buka mata indonesia
3,2026-03-28T03:53:52Z,"[senang, lihat, podcast]","[senang, lihat, podcast]",senang lihat podcast,senang lihat podcast
4,2026-03-27T16:00:24Z,"[simed, ready, receive, this, blessing, from, ...","[simed, ready, receive, this, blessing, from, ...",simed ready receive this blessing from univers...,simed ready receive this blessing from univers...
...,...,...,...,...,...
3538,2025-12-03T09:52:59Z,[herewego],[herewego],herewego,herewego
3539,2025-12-03T09:51:24Z,"[baru, kali, ini, nonton, youtube, konten, nya...","[baru, kali, nonton, youtube, konten, keluar, ...",baru kali nonton youtube konten keluar ditungguin,baru kali nonton youtube konten keluar ditungguin
3540,2025-12-03T09:43:38Z,"[gass, pak, purbaya, kami, masyarakat, selalu,...","[gass, purbaya, masyarakat, selalu, mendukung,...",gass purbaya masyarakat selalu mendukung pejab...,gass purbaya masyarakat selalu dukung jabat pi...
3541,2025-12-03T09:39:18Z,"[yang, ditunggu, tunggu]","[ditunggu, tunggu]",ditunggu tunggu,tunggu tunggu
3542,2025-12-03T09:30:58Z,[here],[here],here,here

Ubah kolom stemmed ke Comment dan simpan ke file hasilPreprocessing .csv

In [26]:
hasil = df[['stemmed']].rename(columns={'stemmed': 'Comment'}).to_csv("data/hasilPreprocessing.csv", index=False)
hasil